name: instant_messaging_app
description: Adventures in instant messaging.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase_core: ^1.10.6
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
